### ISSUE TITLE
java11 macos 报错

### ISSUE THREAD

**Issue by soeyi** [linG5821/Studio3TCrack#1]
` /Applications/Studio 3T.app` 里直接点击jar包显示 ` /Applications/Studio 3T.app`

在控制台里直接 ```  java -jar studio-3t-start.jar  ``` 报错

错误信息: 
```bash
Exception in thread "main" java.lang.NoClassDefFoundError: t3/dataman/mongodb/app/ae
	at start.Start.main(Start.java:7)
Caused by: java.lang.ClassNotFoundException: t3.dataman.mongodb.app.ae
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
```

**Comment by tyfanderw** [comment]
me too

**Comment by linG5821** [comment]
具体的使用方式已经在项目的README文件更新,运行时需要添加虚拟机参数,因为在Mac运行SWT程序必须添加-XstartOnFirstThread参数，详情请查看https://www.eclipse.org/swt/faq.php   # Why does the SWT_AWT bridge not work for me on OS X, even after updating Java or the OS? 使用请查看REAME文件中的使用方法
