### ISSUE TITLE
无法执行，帮忙看看

### ISSUE THREAD

**Issue by gs-liut** [linG5821/Studio3TCrack#16]
D:\>java -cp D:\software\3T Software Labs\Studio 3T\data-man-mongodb-ent-2019.3.0.jar t3.dataman.mongodb.app.ad
错误: 找不到或无法加载主类 Software

D:\>java -cp D:\data-man-mongodb-ent-2019.3.0.jar t3.dataman.mongodb.app.ad
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.BouncyCastleProvider
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more

**Comment by Spider08** [comment]
Getting the same error on windows 7
+1

**Comment by linG5821** [comment]
I'm not sure, from the exception can only know is the problem of dependency, please ask whether there are other Studio3T dependencies in the current directory
