### ISSUE TITLE
Mac 执行报错

### ISSUE THREAD

**Issue by shel-li** [linG5821/Studio3TCrack#18]
步骤：复制Studio3TCrack-2019.2.1内的studio-3t-start-mac.jar到app下Java目录下，执行java -jar -XstartOnFirstThread ./studio-3t-start-mac.jar后报错。
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/start/Studio3TStart : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by linG5821** [comment]
Hello, you should use the Java 8 environment to execute. This package is an old version of the package, so you may not be able to crack Studio3t. We suggest using the new method in RADEME
