### ISSUE TITLE
mac系统报错，如何解决呢

### ISSUE THREAD

**Issue by Kiritoljk** [linG5821/Studio3TCrack#5]
Exception in thread "main" java.lang.NoClassDefFoundError: t3/dataman/mongodb/app/ae
	at com.start.Studio3TStart.main(Studio3TStart.java:9)
Caused by: java.lang.ClassNotFoundException: t3.dataman.mongodb.app.ae
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

**Comment by jackyzonewen** [comment]
me too~

**Comment by linG5821** [comment]
#1 请看一下这个issues
