### ISSUE TITLE
Mac下跑不起来

### ISSUE THREAD

**Issue by augustus2000** [linG5821/Studio3TCrack#6]
版本：10.14.3
studio 3t：2019.1.0
错误信息：Exception in thread "main" java.lang.NoClassDefFoundError: t3/dataman/mongodb/app/ae
	at com.start.Studio3TStart.main(Studio3TStart.java:9)
Caused by: java.lang.ClassNotFoundException: t3.dataman.mongodb.app.ae
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

**Comment by linG5821** [comment]
#1 请看一下这个issues README上也有写运行脚本

**Comment by augustus2000** [comment]
<img width="787" alt="WX20190319-090055@2x" src="https://user-images.githubusercontent.com/12806215/54573066-983eab00-4a25-11e9-96f0-d7414f6404b4.png">
还是不行

**Comment by linG5821** [comment]
请使用绝对路径

**Comment by augustus2000** [comment]
<img width="1060" alt="WX20190319-091312@2x" src="https://user-images.githubusercontent.com/12806215/54573427-3da64e80-4a27-11e9-99c1-2cf3aeb54082.png">
还是一样啊，会不会jdk问题

**Comment by linG5821** [comment]
确实不能在应用程序目录下运行,因为依赖包路径的一些问题，我建议您把安装程序的app目录整个拷贝出来，再次尝试

**Comment by lsxaimm** [comment]
mac下确实不行，按照readme的方式在1.8的jdk，11的jdk环境下都试了，报错：
`
Exception in thread "main" java.lang.NoClassDefFoundError: t3/dataman/mongodb/app/ae
	at com.start.Studio3TStart.main(Studio3TStart.java:9)
Caused by: java.lang.ClassNotFoundException: t3.dataman.mongodb.app.ae
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
`

请问怎么解决啊
