### ISSUE TITLE
Mac 10.14.3运行jar包报错

### ISSUE THREAD

**Issue by Yeelp123** [linG5821/Studio3TCrack#7]
$ sudo java -jar -XstartOnFirstThread ./studio-3t-start-mac.jar
Exception in thread "main" java.lang.NoClassDefFoundError: t3/dataman/mongodb/app/ae
	at com.start.Studio3TStart.main(Studio3TStart.java:9)
Caused by: java.lang.ClassNotFoundException: t3.dataman.mongodb.app.ae
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

**Comment by Yeelp123** [comment]
bogon:app yifuhua$ sudo java -jar -XstartOnFirstThread ./studio-3t-start-mac.jar
Exception in thread "main" java.lang.NoClassDefFoundError: t3/dataman/mongodb/app/ae
	at com.start.Studio3TStart.main(Studio3TStart.java:9)
Caused by: java.lang.ClassNotFoundException: t3.dataman.mongodb.app.ae
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

**Comment by HCLAC** [comment]
me too

**Comment by guoyanbiao520** [comment]
me too

**Comment by linG5821** [comment]
请问一下是否把相关的依赖包拷贝在和studio-3t-start-mac.jar同一目录下？

**Comment by shangfeiSF** [comment]
我也是，mac 10.13.4 jar报报错

**Comment by Yeelp123** [comment]
> 请问一下是否把相关的依赖包拷贝在和studio-3t-start-mac.jar同一目录下？
拷贝了，不管用。

**Comment by linG5821** [comment]
经过我的实际测试确实是可用的  只需要将所有Studio3T依赖的jar包与下载的studio-3t-start-mac.jar启动包放在同一目录运行 java -jar -XstartOnFirstThread ./studio-3t-start-mac.jar

**Comment by linG5821** [comment]
并且确认目录下是否存在data-man-mongodb

**Comment by linG5821** [comment]
或者您可以利用反编译工具直接查看该jar包的源码 ，实际上就一句代码，  尝试自行构建正确的依赖路径  请见谅

**Comment by wsjyz** [comment]
版本问题，混淆后的代码名字不同

**Comment by linG5821** [comment]
谢谢您的解答  新版本可能存在不同的混淆规则
