### ISSUE TITLE
Mac 报错

### ISSUE THREAD

**Issue by blakehan** [linG5821/Studio3TCrack#8]
>java -jar -XstartOnFirstThread /Applications/Studio\ 3T.app/Contents/Resources/app/studio-3t-start-mac.jar

2019-04-11 14:49:32 [main] t3.common.a.a.a.uncaughtException()
INFO: Creating crash flag file.

**Comment by linG5821** [comment]
有更加详细的堆栈信息吗

**Comment by GeekTR** [comment]
老哥你的studio3T是什么版本的，安装包链接给一份吧。新版的这个方法不行了 @linG5821

**Comment by GeekTR** [comment]
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:284)
	at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:238)
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:316)
	at java.util.jar.JarVerifier.update(JarVerifier.java:228)
	at java.util.jar.JarFile.initializeVerifier(JarFile.java:383)
	at java.util.jar.JarFile.getInputStream(JarFile.java:450)
	at sun.misc.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:940)
	at sun.misc.Resource.cachedInputStream(Resource.java:77)
	at sun.misc.Resource.getByteBuffer(Resource.java:160)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:454)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)

**Comment by linG5821** [comment]
请使用最新版的2019.2.1 mac 运行时 需要添加-XstartOnFirstThread 参数 请不要直接将jar包拷贝在APP安装目录下  建议将Resource下的jar包全部拷贝出来在单独的文件夹下 运行java -jar -XstartOnFirstThread start-xxx.jar 如果看到控制台循环打印异常属于正常现象，稍微等待即可具体原因可查看源码

**Comment by cocoongg** [comment]
> 请使用最新版的2019.2.1 mac 运行时 需要添加-XstartOnFirstThread 参数 请不要直接将jar包拷贝在APP安装目录下 建议将Resource下的jar包全部拷贝出来在单独的文件夹下 运行java -jar -XstartOnFirstThread start-xxx.jar 如果看到控制台循环打印异常属于正常现象，稍微等待即可具体原因可查看源码

建议您举个实际的例子，只是这样描述，有很多歧义的。比如：“建议将Resource下的jar包全部拷贝出来在单独的文件夹下 运行java -jar -XstartOnFirstThread start-xxx.jar”这句话，是说Resource下的所有jar包都拷贝出来，然后把start-xxx.jar放到原有目录里？还是说放到新的目录里，有歧义，还是举个例子比较清晰
